name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          zig-version: 0.14.0
      
      - name: Build project
        run: zig build
